// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-refined/LuminousDepth.tsx": () => import("../components/mockups/portfolio-refined/LuminousDepth.tsx"),
  "./components/mockups/portfolio-refined/RazorEdge.tsx": () => import("../components/mockups/portfolio-refined/RazorEdge.tsx"),
  "./components/mockups/portfolio-vibes/ForestDusk.tsx": () => import("../components/mockups/portfolio-vibes/ForestDusk.tsx"),
  "./components/mockups/portfolio-vibes/LiquidChrome.tsx": () => import("../components/mockups/portfolio-vibes/LiquidChrome.tsx"),
  "./components/mockups/portfolio-vibes/ObsidianEmber.tsx": () => import("../components/mockups/portfolio-vibes/ObsidianEmber.tsx")
};
